version: '3.8'

services:
  avito-app:
    build: ./
    command: ./wait-for-postgres.sh db ./avito-app
    ports:
      - 8000:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=postgres

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5436:5432